# Generated by Django 2.2.8 on 2019-12-19 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191219_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='code',
            field=models.OneToOneField(default='000000', max_length=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
