# Generated by Django 2.2.8 on 2019-12-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_phone_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='code1',
        ),
    ]
