# Generated by Django 2.2.8 on 2019-12-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_myusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUsers',
        ),
    ]
