# Generated by Django 3.0 on 2019-12-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('seasons', models.CharField(max_length=10)),
                ('begin_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=1000)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieDirector')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=1000)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.MovieDirector')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=1000)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie')),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.TVShow')),
            ],
        ),
    ]
