# Generated by Django 3.0 on 2019-12-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20191206_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedirector',
            old_name='dir_name',
            new_name='name',
        ),
    ]
