# Generated by Django 3.0 on 2019-12-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20191206_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='tvshow',
        ),
        migrations.DeleteModel(
            name='TVShow',
        ),
    ]
