# Generated by Django 3.0 on 2019-12-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20191206_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedirector',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
