# Generated by Django 3.0 on 2019-12-06 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_moviedirector_is_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='moviedirector',
            name='age',
        ),
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='moviedirector',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
