# Generated by Django 3.0 on 2019-12-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20191206_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='role',
            field=models.CharField(default='0000000', max_length=500),
        ),
    ]
