# Generated by Django 3.0 on 2019-12-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20191207_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
