# Generated by Django 3.0 on 2019-12-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_actor_is_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='photo',
        ),
    ]
