# Generated by Django 3.0 on 2019-12-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20191208_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='role',
        ),
    ]
