# Generated by Django 3.0 on 2019-12-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_remove_actor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='namw',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
