# Generated by Django 3.0 on 2019-12-08 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_actor_namw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='namw',
        ),
    ]
