# Generated by Django 3.0 on 2019-12-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20191211_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_favorite',
        ),
    ]
