# Generated by Django 2.2.8 on 2019-12-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_auto_20191212_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created',
        ),
    ]
